name: XenonMinecraftPlugin
version: 0.1.0
main: global.minecraft.XenonMinecraftPlugin
authors: [ Iapetus11 ]
description: A plugin with a bunch of miscellaneous features for Xenon
commands:
  shrug:
    description: The Discord /shrug but in Minecraft
    usage: /<command>
    permission: xenon.command.shrug